{"name": "test_boken_xfail", "status": "skipped", "statusDetails": {"message": "Exception: 中断异常", "trace": "@pytest.mark.xfail\n    def test_boken_xfail():\n>       broken_fixture()\n\ntest_pytest_assert.py:31: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n    def broken_fixture():\n        print(\"开发这个模块没修改好\")\n>       raise Exception(\"中断异常\")\nE       Exception: 中断异常\n\ntest_pytest_assert.py:27: Exception"}, "start": 1596702827508, "stop": 1596702827509, "uuid": "d207b0a5-6984-43b1-8152-fe6bf4203ee3", "historyId": "d298f732358a9b077d2fc30965f16562", "testCaseId": "90a0bc0be811270db7613efe45dd3839", "fullName": "test_pytest_assert#test_boken_xfail", "labels": [{"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "suite", "value": "test_pytest_assert"}, {"name": "host", "value": "DESKTOP-RU1KMSM"}, {"name": "thread", "value": "2240-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest_assert"}]}